### ISSUE TITLE
Ubuntu Server 16.04.3 error on npm install

### ISSUE THREAD

**Issue by JuezFenix** [AndiDittrich/HttpErrorPages#5]
Hi, 
I have an error when launch npm install on the /opt/HttpErrorPages/ directory.

Paste the log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
...
10562 silly rollbackFailedOptional Finishing
10563 silly runTopLevelLifecycles Starting
10564 silly runTopLevelLifecycles Finishing
10565 silly install printInstalled
10566 verbose stack Error: node-sass@4.7.2 install: `node scripts/install.js`
10566 verbose stack spawn ENOENT
10566 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
10566 verbose stack     at emitTwo (events.js:87:13)
10566 verbose stack     at ChildProcess.emit (events.js:172:7)
10566 verbose stack     at maybeClose (internal/child_process.js:821:16)
10566 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10567 verbose pkgid node-sass@4.7.2
10568 verbose cwd /opt/HttpErrorPages
10569 error Linux 4.4.0-101-generic
10570 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
10571 error node v4.2.6
10572 error npm  v3.5.2
10573 error file sh
10574 error code ELIFECYCLE
10575 error errno ENOENT
10576 error syscall spawn
10577 error node-sass@4.7.2 install: `node scripts/install.js`
10577 error spawn ENOENT
10578 error Failed at the node-sass@4.7.2 install script 'node scripts/install.js'.
10578 error Make sure you have the latest version of node.js and npm installed.
10578 error If you do, this is most likely a problem with the node-sass package,
10578 error not with npm itself.
10578 error Tell the author that this fails on your system:
10578 error     node scripts/install.js
10578 error You can get information on how to open an issue for this project with:
10578 error     npm bugs node-sass
10578 error Or if that isn't available, you can get their info via:
10578 error     npm owner ls node-sass
10578 error There is likely additional logging output above.
10579 verbose exit [ 1, true ]

Whats the problem??

**Comment by AndiDittrich** [comment]
Hi,

please try to install it without the dev dependencies

```terminal
npm install http-error-pages --production
```

the error log above shows some errors regarding `node-sass` which is only used to compile the scss to css.
i will take a look on it later

best regards, Andi

**Comment by AndiDittrich** [comment]
hi JuezFenix,
i cannot reproduce your issue...but it seems that you are using a very old nodejs+npm version...

```terminal
andi@epic:/opt/test$ npm install http-error-pages
npm WARN saveError ENOENT: no such file or directory, open '/opt/test/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/opt/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ http-error-pages@1.0.0
added 18 packages in 3.835s
andi@epic:/opt/test$ la
node_modules  package-lock.json
andi@epic:/opt/test$ ls -all
total 20
drwxr-xr-x  3 andi andi 4096 Dez  7 11:23 .
drwxr-xr-x  5 root root 4096 Dez  7 11:23 ..
drwxrwxr-x 21 andi andi 4096 Dez  7 11:23 node_modules
-rw-rw-r--  1 andi andi 4672 Dez  7 11:23 package-lock.json
andi@epic:/opt/test$ npm -v
5.5.1
andi@epic:/opt/test$ node -v
v9.2.0
andi@epic:/opt/test$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by JuezFenix** [comment]
The version I use are de apt repositories on Ubuntu 16.04. Should I use other version?

**Comment by AndiDittrich** [comment]
of course... the http-error-pages **express.js** integration requires node >= 7.6

but what do you want to achive ? the npm package is only required in case you use express.js

**Comment by JuezFenix** [comment]
I want to use another language and maybe other footer.

**Comment by AndiDittrich** [comment]
oh ok, in this case you need a recent [node.js and npm version](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)

here is an example howto re-build the pages - **you have to clone** the repository (npm package installation is not suitible for this case)

```terminal
 $ wget https://github.com/AndiDittrich/HttpErrorPages/archive/master.zip
2017-12-07 20:51:48 (396 KB/s) - ‘master.zip’ saved [135343]

andi@sapphire /opt/test
 $ unzip master.zip
Archive:  master.zip
6b5c030200cadbb0531420c75e0ec29d8ba04de9
   creating: HttpErrorPages-master/
  inflating: HttpErrorPages-master/.eslintrc
  inflating: HttpErrorPages-master/.gitignore
  inflating: HttpErrorPages-master/CHANGES.md
  inflating: HttpErrorPages-master/LICENSE.md
  inflating: HttpErrorPages-master/README.md
   creating: HttpErrorPages-master/assets/
  inflating: HttpErrorPages-master/assets/layout.css
  inflating: HttpErrorPages-master/assets/layout.scss
  inflating: HttpErrorPages-master/assets/normalize-5.0.0.css
  inflating: HttpErrorPages-master/assets/screenshot1.png
  inflating: HttpErrorPages-master/assets/template.ejs
   creating: HttpErrorPages-master/bin/
  inflating: HttpErrorPages-master/bin/generator.js
  inflating: HttpErrorPages-master/config-dist.json
  inflating: HttpErrorPages-master/config.json
   creating: HttpErrorPages-master/dist/
  inflating: HttpErrorPages-master/dist/HTTP400.html
  inflating: HttpErrorPages-master/dist/HTTP401.html
  inflating: HttpErrorPages-master/dist/HTTP403.html
  inflating: HttpErrorPages-master/dist/HTTP404.html
  inflating: HttpErrorPages-master/dist/HTTP500.html
  inflating: HttpErrorPages-master/dist/HTTP501.html
  inflating: HttpErrorPages-master/dist/HTTP502.html
  inflating: HttpErrorPages-master/dist/HTTP503.html
  inflating: HttpErrorPages-master/dist/HTTP520.html
  inflating: HttpErrorPages-master/dist/HTTP521.html
  inflating: HttpErrorPages-master/dist/HTTP533.html
  inflating: HttpErrorPages-master/dist/pages.tar
   creating: HttpErrorPages-master/docs/
  inflating: HttpErrorPages-master/docs/HTTP400.html
  inflating: HttpErrorPages-master/docs/HTTP401.html
  inflating: HttpErrorPages-master/docs/HTTP403.html
  inflating: HttpErrorPages-master/docs/HTTP404.html
  inflating: HttpErrorPages-master/docs/HTTP500.html
  inflating: HttpErrorPages-master/docs/HTTP501.html
  inflating: HttpErrorPages-master/docs/HTTP502.html
  inflating: HttpErrorPages-master/docs/HTTP503.html
  inflating: HttpErrorPages-master/docs/HTTP520.html
  inflating: HttpErrorPages-master/docs/HTTP521.html
  inflating: HttpErrorPages-master/docs/HTTP533.html
  inflating: HttpErrorPages-master/docs/README.md
  inflating: HttpErrorPages-master/docs/config.json
  inflating: HttpErrorPages-master/express-demo.js
  inflating: HttpErrorPages-master/gulpfile.js
 extracting: HttpErrorPages-master/http-error-pages
   creating: HttpErrorPages-master/i18n/
  inflating: HttpErrorPages-master/i18n/pages-en_US.json
  inflating: HttpErrorPages-master/i18n/pages-pt_BR.json
   creating: HttpErrorPages-master/lib/
  inflating: HttpErrorPages-master/lib/README.md
  inflating: HttpErrorPages-master/lib/dispatcher.js
  inflating: HttpErrorPages-master/lib/error-handler.js
  inflating: HttpErrorPages-master/lib/json-reader.js
  inflating: HttpErrorPages-master/lib/page-renderer.js
  inflating: HttpErrorPages-master/package.json
  inflating: HttpErrorPages-master/yarn.lock

andi@sapphire /opt/test
 $ cd HttpErrorPages-master/

andi@sapphire /opt/test/HttpErrorPages-master
 $ yarn install
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 6.65s.

andi@sapphire /opt/test/HttpErrorPages-master
 $ npm run gulp

> http-error-pages@1.0.0 gulp /opt/test/HttpErrorPages-master
> gulp

[20:52:36] Using gulpfile /opt/test/HttpErrorPages-master/gulpfile.js
[20:52:36] Starting 'sass'...
[20:52:36] Finished 'sass' after 94 ms
[20:52:36] Starting 'default'...
[20:52:36] Finished 'default' after 38 μs

andi@sapphire /opt/test/HttpErrorPages-master
 $ npm run static

> http-error-pages@1.0.0 static /opt/test/HttpErrorPages-master
> node bin/generator.js static


Paths
 |- Config: /opt/test/HttpErrorPages-master/config.json
 |- Template: /opt/test/HttpErrorPages-master/assets/template.ejs
 |- Styles: /opt/test/HttpErrorPages-master/assets/layout.css
 |- Pages: /opt/test/HttpErrorPages-master/i18n/pages-en_US.json

Generating static pages
 |- Page <HTTP400.html>
 |- Page <HTTP404.html>
 |- Page <HTTP401.html>
 |- Page <HTTP500.html>
 |- Page <HTTP501.html>
 |- Page <HTTP502.html>
 |- Page <HTTP503.html>
 |- Page <HTTP521.html>
 |- Page <HTTP520.html>
 |- Page <HTTP533.html>
 |- Page <HTTP403.html>
Static files generated

```

**Comment by JuezFenix** [comment]
Imposible to install npm (nodejs install ok)

![captura](https://user-images.githubusercontent.com/11253951/33789961-c925cea0-dc7c-11e7-83f4-25f7d798297b.PNG)

yarn install fails....
